apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-sub
  template:
    metadata:
      labels:
        name: nats-sub
    spec:
      containers:
        - name: nats-sub
          image: nats-sub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: nats-subp
