kind: ServiceAccount
apiVersion: v1
metadata:
  name: micro-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-api
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "4222,5432,6379,443,80"
        linkerd.io/inject: disabled
      creationTimestamp: null
      labels:
        name: micro-api
    spec:
      serviceAccountName: micro-api
      containers:
        - name: api
          env:
            - name: MICRO_API_ADDRESS
              value: ":8080"
            - name: MICRO_API_HANDLER
              value: "api"
            - name: MICRO_ENABLE_STATS
              value: "true"
          args:
            - api
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: micro-api-port
status: {}
