apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      containers:
        - name: api
          env:
            - name: MICRO_API_ADDRESS
              value: ':8080'
            - name: MICRO_API_HANDLER
              value: 'api'
            - name: MICRO_ENABLE_STATS
              value: 'true'
          args:
            - api
          image: microhq/micro:kubernetes
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: micro-api-port
