apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-test
  template:
    metadata:
      labels:
        name: nats-test
    spec:
      containers:
        - name: nats-test
          image: nats-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: nats-testp
